#!/usr/bin/python3
import re as regex

#
# static const char cityName[1000][4]
# {
# 		{"1", "2", "3", "4"},

with open("output", "r") as userfile, open("variable", "w") as var:
	var.write("static const char cityName[1000][4]\n{\n");
	for line in userfile.readlines():
		result = regex.search("(.*):(.*):(.*):(.*):", line);
		try:
			var.write("\t{ \"" + result.group(1) + "\", \"" + result.group(2) + "\", \"" + result.group(3) + "\", \"" + result.group(4) + "\"},\n\t"); 
		except:
			pass
	var.write("\n};\n");
		
